spring:
  application:
    name: ai-app
  profiles:
    active: local # 激活存放密钥的profile
server:
  port: 8081

# 大模型配置
langchain4j:
  open-ai:
    chat-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: demo
      model-name: gpt-4o-mini
    streaming-chat-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: demo
      model-name: gpt-4o-mini
    qwen-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-max
      max-tokens: 100
      log-requests: true
      log-responses: true
    deepseek-chat-model:
      base-url: https://api.chatanywhere.tech
      model-name: deepseek-r1
      max-tokens: 100
      log-requests: true
      log-responses: true
    gemini-chat-model:
      base-url: https://generativelanguage.googleapis.com/v1beta
      model-name: gemini-2.5-pro
      max-tokens: 100
      log-requests: true
      log-responses: true